name: Build and Deploy Flutter Web App

on: 
  repository_dispatch:
    types: [custom_event]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: VARIABLES
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/agronota-app 
          token: ${{ secrets.AGRONOTA_APP }}
          path: otimizai
          ref: main 

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
            flutter-version: '3.22.2'

      - name: Flutter build
        working-directory: otimizai/otimizai
        run: |
            flutter pub upgrade --major-versions
            flutter pub get
            flutter build web --dart-define=FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
        # Importante: O comando flutter build web --release n√£o √© mais necess√°rio
        # e para que o build funcione no GitHub Actions, √© necess√°rio ter a pasta web no diret√≥rio raiz do projeto

      - name: Format index.html
        working-directory: otimizai/otimizai
        run: |
          python -c "import os
          import re
          index_file_path = 'build/web/index.html'
          with open(index_file_path, 'r', encoding='utf-8') as file:
              content = file.read()
          content = re.sub(r'href=\"/*', 'href=\"./', content)
          content = re.sub(r'<meta name=\"description\" content=\"A new Flutter project.\">', '<meta name=\"description\" content=\"Solu√ß√£o para o agroneg√≥cio\">', content)
          content = re.sub(r'<meta name=\"apple-mobile-web-app-title\" content=\"otimizai_agronota_app\">', '<meta name=\"apple-mobile-web-app-title\" content=\"Otimizai\">', content)
          content = re.sub(r'<title>otimizai_agronota_app</title>', '<title>Otimizai</title>', content)
          with open(index_file_path, 'w', encoding='utf-8') as file:
              file.write(content)"

      - name: Deploy web app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.AGRONOTA_PWA }}
          publish_dir: otimizai/otimizai/build/web
          publish_branch: gh-pages
          commit_message: 'Deploy Flutter Web App üöÄ'